package: yform_adminer
version: '1.4.1'
author: 'FriendsOfRedaxo | Christoph Böcker'
supportpage: https://github.com/FriendsOfREDAXO/yform_adminer

requires:
    redaxo: '^5.15.0'
    packages:
        yform: '^4.0.0'
        yform/manager: '^4.0.0'
        dminer: '^1'
    php:
        version: '^8.1'
