package: yform_adminer
version: '1.4.0'
author: 'FriendsOfRedaxo | Christoph Böcker'
supportpage: https://github.com/FriendsOfREDAXO/yform_adminer

requires:
    redaxo: '^5.15.0'
    yform: '^4.0.0'
    adminer: '^1'
    php:
        version: '^8.1'
