package: yform_adminer
version: '1.5.0'
author: 'FriendsOfRedaxo | Christoph Böcker'
supportpage: https://github.com/FriendsOfREDAXO/yform_adminer

requires:
    redaxo: '^5.15.0'
    packages:
        yform: '^4.0.0'
        yform/manager: '^4.0.0'
        adminer: '>=1.0, <3'
    php:
        version: '^8.1'
